// flow-typed signature: 9526468d25844a84903881d1375b5648
// flow-typed version: <<STUB>>/apollo-link_v^0.5.4/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link/dist/src/index' {
  declare module.exports: any;
}

declare module 'apollo-link/dist/tests/tests' {
  declare module.exports: any;
}

declare module 'apollo-link/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link/dist/src/index.js' {
  declare module.exports: $Exports<'apollo-link/dist/src/index'>;
}
declare module 'apollo-link/dist/tests/tests.js' {
  declare module.exports: $Exports<'apollo-link/dist/tests/tests'>;
}
declare module 'apollo-link/lib/index.js' {
  declare module.exports: $Exports<'apollo-link/lib/index'>;
}
